'use strict';var binana={};import{AssertionError,AttributeError,BaseException,DeprecationWarning,Exception,IndexError,IterableError,KeyError,NotImplementedError,RuntimeWarning,StopIteration,UserWarning,ValueError,Warning,__JsIterator__,__PyIterator__,__Terminal__,__add__,__and__,__call__,__class__,__envir__,__eq__,__floordiv__,__ge__,__get__,__getcm__,__getitem__,__getslice__,__getsm__,__gt__,__i__,__iadd__,__iand__,__idiv__,__ijsmod__,__ilshift__,__imatmul__,__imod__,__imul__,__in__,__init__,__ior__,
__ipow__,__irshift__,__isub__,__ixor__,__jsUsePyNext__,__jsmod__,__k__,__kwargtrans__,__le__,__lshift__,__lt__,__matmul__,__mergefields__,__mergekwargtrans__,__mod__,__mul__,__ne__,__neg__,__nest__,__or__,__pow__,__pragma__,__proxy__,__pyUseJsNext__,__rshift__,__setitem__,__setproperty__,__setslice__,__sort__,__specialattrib__,__sub__,__super__,__t__,__terminal__,__truediv__,__withblock__,__xor__,abs,all,any,assert,bool,bytearray,bytes,callable,chr,copy,deepcopy,delattr,dict,dir,divmod,enumerate,
filter,float,getattr,hasattr,input,int,isinstance,issubclass,len,list,map,max,min,object,ord,pow,print,property,py_TypeError,py_iter,py_metatype,py_next,py_reversed,py_typeof,range,repr,round,set,setattr,sorted,str,sum,tuple,zip}from"./org.transcrypt.__runtime__.js";import{fabs}from"./binana.shim.js";import*as __module_binana__ from"./binana.js";__nest__(binana,"",__module_binana__);var __name__="binana.output.main";export var os=binana.os;export var textwrap=binana.shim;export var sys=binana.sys;
export var write_all_output=function(parameters,ligand,receptor,closest,close,hydrogen_bonds,hydrophobics,pi_pi,salt_bridges,ligand_atom_types,electrostatic_energies,flexibility,pi_cat){if(parameters.params["output_dir"]!=""&&!os.path.exists(parameters.params["output_dir"]))os.mkdir(parameters.params["output_dir"]);var json_output=binana.output.json_out.json_file(closest["labels"],close["labels"],hydrogen_bonds["labels"],hydrophobics["labels"],pi_pi["labels"]["pi_stacking"],pi_pi["labels"]["T_stacking"],
pi_cat["labels"],salt_bridges["labels"],ligand.filename,receptor.filename);print("json output:");print(json_output);var output=binana.output.log.make_log(parameters,ligand,ligand_atom_types["counts"],closest["counts"],closest["labels"],close["counts"],close["labels"],electrostatic_energies["counts"],flexibility["counts"],hydrogen_bonds["counts"],hydrogen_bonds["labels"],hydrophobics["counts"],hydrophobics["labels"],pi_pi["counts"],pi_pi["labels"]["pi_stacking"],pi_pi["labels"]["T_stacking"],pi_cat["labels"],
salt_bridges["counts"],salt_bridges["labels"]);closest["mol"].set_resname("CCN");close["mol"].set_resname("CON");flexibility["mols"]["alpha_helix"].set_resname("ALP");flexibility["mols"]["beta_sheet"].set_resname("BET");flexibility["mols"]["other_2nd_structure"].set_resname("OTH");flexibility["mols"]["back_bone"].set_resname("BAC");flexibility["mols"]["side_chain"].set_resname("SID");hydrophobics["mol"].set_resname("HYD");hydrogen_bonds["mol"].set_resname("HBN");pi_pi["mols"]["pi_stacking"].set_resname("PIS");
pi_pi["mols"]["T_stacking"].set_resname("PIT");pi_cat["mol"].set_resname("PIC");salt_bridges["mol"].set_resname("SAL");ligand.set_resname("LIG");if(parameters.params["output_dir"]!=""){binana.output.dir.pdbs.output_dir_pdbs(closest["mol"],parameters,close["mol"],flexibility["mols"]["alpha_helix"],flexibility["mols"]["beta_sheet"],flexibility["mols"]["other_2nd_structure"],flexibility["mols"]["back_bone"],flexibility["mols"]["side_chain"],hydrophobics["mol"],hydrogen_bonds["mol"],pi_pi["mols"]["pi_stacking"],
pi_pi["mols"]["T_stacking"],pi_cat["mol"],salt_bridges["mol"],ligand,receptor);binana.output.dir.vmd_state.vmd_state_file(parameters)}if(parameters.params["output_file"]!="")binana.output.single_file.make_single_file(parameters,receptor,ligand,closest["mol"],close["mol"],flexibility["mols"]["alpha_helix"],flexibility["mols"]["beta_sheet"],flexibility["mols"]["other_2nd_structure"],flexibility["mols"]["back_bone"],flexibility["mols"]["side_chain"],hydrophobics["mol"],hydrogen_bonds["mol"],pi_pi["mols"]["pi_stacking"],
pi_pi["mols"]["T_stacking"],pi_cat["mol"],salt_bridges["mol"],output)};

//# sourceMappingURL=binana.output.main.map